on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v5
      - name: KK
        run: |
          echo $GITHUB_ACTION
          echo $GITHUB_RUN_NUMBER
          echo $GITHUB_RUN_ID
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
